################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 
OBJCOPY_BIN := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Application \
Core/Src \
Core/Startup \
Drivers/BSP/Components/IMX335 \
Drivers/BSP/STM32N6570-DK \
Drivers/CMSIS/DSP/ComputeLibrary/Source \
Drivers/CMSIS/DSP/Examples/ARM/arm_bayes_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_bayes_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_bayes_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_bayes_example/RTE/Device/ARMCM55 \
Drivers/CMSIS/DSP/Examples/ARM/arm_bayes_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_bayes_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example/RTE/Device/ARMCM55 \
Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example/RTE/Device/ARMCM55 \
Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example/RTE/Device/ARMCM55 \
Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example/RTE/Device/ARMCM55 \
Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example/RTE/Device/ARMCM55 \
Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example/RTE/Device/ARMCM55 \
Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example/RTE/Device/ARMCM55 \
Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example/RTE/Device/ARMCM55 \
Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example/RTE/Device/ARMCM55 \
Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example/RTE/Device/ARMCM55 \
Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_svm_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_svm_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_svm_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_svm_example/RTE/Device/ARMCM55 \
Drivers/CMSIS/DSP/Examples/ARM/arm_svm_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_svm_example \
Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example/RTE/Device/ARMCM0 \
Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example/RTE/Device/ARMCM3 \
Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example/RTE/Device/ARMCM4_FP \
Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example/RTE/Device/ARMCM55 \
Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example/RTE/Device/ARMCM7_SP \
Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example \
Drivers/CMSIS/DSP/Source/BasicMathFunctions \
Drivers/CMSIS/DSP/Source/BayesFunctions \
Drivers/CMSIS/DSP/Source/CommonTables \
Drivers/CMSIS/DSP/Source/ComplexMathFunctions \
Drivers/CMSIS/DSP/Source/ControllerFunctions \
Drivers/CMSIS/DSP/Source/DistanceFunctions \
Drivers/CMSIS/DSP/Source/FastMathFunctions \
Drivers/CMSIS/DSP/Source/FilteringFunctions \
Drivers/CMSIS/DSP/Source/InterpolationFunctions \
Drivers/CMSIS/DSP/Source/MatrixFunctions \
Drivers/CMSIS/DSP/Source/QuaternionMathFunctions \
Drivers/CMSIS/DSP/Source/SVMFunctions \
Drivers/CMSIS/DSP/Source/StatisticsFunctions \
Drivers/CMSIS/DSP/Source/SupportFunctions \
Drivers/CMSIS/DSP/Source/TransformFunctions \
Drivers/CMSIS \
Drivers/STM32N6xx_HAL_Driver \
Middlewares/AI_Runtime/Npu/Devices/STM32N6XX \
Middlewares/AI_Runtime/Npu/ll_aton \
Middlewares/Camera_Middleware/ISP_Library/isp/Src \
Middlewares/Camera_Middleware/ISP_Library/isp/USB_Device/Src \
Middlewares/Camera_Middleware \
Middlewares/Camera_Middleware/sensors \
Middlewares/Camera_Middleware/sensors/imx335 \
Middlewares/Camera_Middleware/sensors/vd55g1 \
Middlewares/Camera_Middleware/sensors/vd6g \
Middlewares/STM32_ISP \
Middlewares/ai-postprocessing-wrapper \
Middlewares/lib_vision_models_pp/lib_vision_models_pp/Src \
Model/NUCLEO-N657X0-Q \
Model/STM32N6570-DK \
Model/st_ai_output \
Model/st_ai_ws/build_network \
Model/st_ai_ws/neural_art__network \
Model/st_ai_ws/neural_art__network/tracer_workspace/working_dir \
Utilities/Fonts \
Utilities/lcd \
mtk3_bsp2/mtkernel/device/adc \
mtk3_bsp2/mtkernel/device/adc/sysdepend/rx231 \
mtk3_bsp2/mtkernel/device/adc/sysdepend/rx65n \
mtk3_bsp2/mtkernel/device/adc/sysdepend/rza2m \
mtk3_bsp2/mtkernel/device/adc/sysdepend/stm32h7 \
mtk3_bsp2/mtkernel/device/adc/sysdepend/stm32l4 \
mtk3_bsp2/mtkernel/device/adc/sysdepend/tx03_m367 \
mtk3_bsp2/mtkernel/device/common/drvif \
mtk3_bsp2/mtkernel/device/i2c \
mtk3_bsp2/mtkernel/device/i2c/sysdepend/rx231 \
mtk3_bsp2/mtkernel/device/i2c/sysdepend/rx65n \
mtk3_bsp2/mtkernel/device/i2c/sysdepend/rza2m \
mtk3_bsp2/mtkernel/device/i2c/sysdepend/stm32h7 \
mtk3_bsp2/mtkernel/device/i2c/sysdepend/stm32l4 \
mtk3_bsp2/mtkernel/device/i2c/sysdepend/tx03_m367 \
mtk3_bsp2/mtkernel/device/ser \
mtk3_bsp2/mtkernel/device/ser/sysdepend/rx231 \
mtk3_bsp2/mtkernel/device/ser/sysdepend/rx65n \
mtk3_bsp2/mtkernel/device/ser/sysdepend/rza2m \
mtk3_bsp2/mtkernel/device/ser/sysdepend/stm32h7 \
mtk3_bsp2/mtkernel/device/ser/sysdepend/stm32l4 \
mtk3_bsp2/mtkernel/device/ser/sysdepend/tx03_m367 \
mtk3_bsp2/mtkernel/kernel/inittask \
mtk3_bsp2/mtkernel/kernel/sysdepend/cpu/core/armv7a \
mtk3_bsp2/mtkernel/kernel/sysdepend/cpu/core/armv7m \
mtk3_bsp2/mtkernel/kernel/sysdepend/cpu/core/rxv2 \
mtk3_bsp2/mtkernel/kernel/sysdepend/cpu/rx231 \
mtk3_bsp2/mtkernel/kernel/sysdepend/cpu/rx65n \
mtk3_bsp2/mtkernel/kernel/sysdepend/cpu/rza2m \
mtk3_bsp2/mtkernel/kernel/sysdepend/cpu/stm32h7 \
mtk3_bsp2/mtkernel/kernel/sysdepend/cpu/stm32l4 \
mtk3_bsp2/mtkernel/kernel/sysdepend/cpu/tx03_m367 \
mtk3_bsp2/mtkernel/kernel/sysdepend/iote_m367 \
mtk3_bsp2/mtkernel/kernel/sysdepend/iote_rx231 \
mtk3_bsp2/mtkernel/kernel/sysdepend/iote_rza2m \
mtk3_bsp2/mtkernel/kernel/sysdepend/iote_stm32l4 \
mtk3_bsp2/mtkernel/kernel/sysinit \
mtk3_bsp2/mtkernel/kernel/tkernel \
mtk3_bsp2/mtkernel/kernel/tstdlib \
mtk3_bsp2/mtkernel/kernel/usermain \
mtk3_bsp2/mtkernel/lib/libtk \
mtk3_bsp2/mtkernel/lib/libtk/sysdepend/cpu/core/armv7a \
mtk3_bsp2/mtkernel/lib/libtk/sysdepend/cpu/core/armv7m \
mtk3_bsp2/mtkernel/lib/libtk/sysdepend/cpu/core/rxv2 \
mtk3_bsp2/mtkernel/lib/libtk/sysdepend/cpu/rx231 \
mtk3_bsp2/mtkernel/lib/libtk/sysdepend/cpu/rx65n \
mtk3_bsp2/mtkernel/lib/libtk/sysdepend/cpu/rza2m \
mtk3_bsp2/mtkernel/lib/libtk/sysdepend/cpu/stm32h7 \
mtk3_bsp2/mtkernel/lib/libtk/sysdepend/cpu/stm32l4 \
mtk3_bsp2/mtkernel/lib/libtk/sysdepend/cpu/tx03_m367 \
mtk3_bsp2/mtkernel/lib/libtm \
mtk3_bsp2/mtkernel/lib/libtm/sysdepend/iote_m367 \
mtk3_bsp2/mtkernel/lib/libtm/sysdepend/iote_rx231 \
mtk3_bsp2/mtkernel/lib/libtm/sysdepend/iote_rza2m \
mtk3_bsp2/mtkernel/lib/libtm/sysdepend/iote_stm32l4 \
mtk3_bsp2/mtkernel/lib/libtm/sysdepend/no_device \
mtk3_bsp2/sysdepend/nxp_mcux/cpu/core/armv8m \
mtk3_bsp2/sysdepend/nxp_mcux/device/hal_adc \
mtk3_bsp2/sysdepend/nxp_mcux/device/hal_lpi2c \
mtk3_bsp2/sysdepend/nxp_mcux \
mtk3_bsp2/sysdepend/nxp_mcux/lib/libtk/cpu/core/armv8m \
mtk3_bsp2/sysdepend/nxp_mcux/lib/libtm/evk_lpc55s69 \
mtk3_bsp2/sysdepend/nxp_mcux/lib/libtm/frdm_mcxn947 \
mtk3_bsp2/sysdepend/ra_fsp/cpu/core/armv7m \
mtk3_bsp2/sysdepend/ra_fsp/cpu/core/armv8m \
mtk3_bsp2/sysdepend/ra_fsp/device/hal_adc \
mtk3_bsp2/sysdepend/ra_fsp/device/hal_i2c \
mtk3_bsp2/sysdepend/ra_fsp/device/hal_i3c_i2c \
mtk3_bsp2/sysdepend/ra_fsp/device/hal_sci_i2c \
mtk3_bsp2/sysdepend/ra_fsp \
mtk3_bsp2/sysdepend/ra_fsp/lib/libtk/cpu/core/armv7m \
mtk3_bsp2/sysdepend/ra_fsp/lib/libtk/cpu/core/armv8m \
mtk3_bsp2/sysdepend/ra_fsp/lib/libtm/arduino_unor4 \
mtk3_bsp2/sysdepend/ra_fsp/lib/libtm/clicker_ra4m1 \
mtk3_bsp2/sysdepend/ra_fsp/lib/libtm/ek_ra6m3 \
mtk3_bsp2/sysdepend/ra_fsp/lib/libtm/ek_ra8d1 \
mtk3_bsp2/sysdepend/ra_fsp/lib/libtm/ek_ra8m1 \
mtk3_bsp2/sysdepend/stm32_cube/cpu/core/armv7m \
mtk3_bsp2/sysdepend/stm32_cube/cpu/core/armv8m \
mtk3_bsp2/sysdepend/stm32_cube/device/hal_adc \
mtk3_bsp2/sysdepend/stm32_cube/device/hal_adc/sysdepend \
mtk3_bsp2/sysdepend/stm32_cube/device/hal_i2c \
mtk3_bsp2/sysdepend/stm32_cube \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtk/cpu/core/armv7m \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtk/cpu/core/armv8m \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtk/cpu/stm32f4 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtk/cpu/stm32f7 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtk/cpu/stm32g4 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtk/cpu/stm32h7 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtk/cpu/stm32l4 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtk/cpu/stm32n6 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtk \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/discovery_stm32n657 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/nucleo_stm32f401 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/nucleo_stm32f411 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/nucleo_stm32f446 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/nucleo_stm32f767 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/nucleo_stm32g431 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/nucleo_stm32g491 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/nucleo_stm32h723 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/nucleo_stm32l476 \
mtk3_bsp2/sysdepend/stm32_cube/lib/libtm/nucleo_stm32l4r5 \
mtk3_bsp2/sysdepend/xmc_mtb/cpu/core/armv7m \
mtk3_bsp2/sysdepend/xmc_mtb/cpu/xmc7200 \
mtk3_bsp2/sysdepend/xmc_mtb/device/hal_adc \
mtk3_bsp2/sysdepend/xmc_mtb/device/hal_adc/sysdepend/xmc7200 \
mtk3_bsp2/sysdepend/xmc_mtb/device/hal_i2c \
mtk3_bsp2/sysdepend/xmc_mtb/device/hal_i2c/sysdepend/xmc7200 \
mtk3_bsp2/sysdepend/xmc_mtb \
mtk3_bsp2/sysdepend/xmc_mtb/lib/libtk/cpu/core/armv7m \
mtk3_bsp2/sysdepend/xmc_mtb/lib/libtk/cpu/xmc7200 \
mtk3_bsp2/sysdepend/xmc_mtb/lib/libtm/evk_xmc7200 \

